#cloud-config
users:
  - name: subquery
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa <key>
package_update: true
package_upgrade: true
packages:
  - gcc
  - make
  - jq
runcmd:
  - echo "Done" > /root/status.txt
  