{
 "title": "Pathrock Overview",
 "description": "A custom built dashboard that displays the status of all services.",
 "tags": [ "Custom" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Physical Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "RPC1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"162.55.85.47:9100\",job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"46.4.123.170:9100\",job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"141.95.97.30:9100\",job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQIDB1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"168.119.212.48:9100\",job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGD.PROXY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"sgd.proxy.pathrocknetwork.org:8405\",job=\"haproxy\"}",
     "legendFormat": "sgd.proxy.pathrocknetowrk.org"
    }
   ]
  },
  { "title": "RPC Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Moonbase Alpha Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "moonbeam_substrate_sync_peers{chain=\"moonbase_alpha\",instance=\"46.4.123.170:9212\",job=\"moonbase\"}",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "Kusama Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"ksmcc3\",instance=~\"162\\\\.55\\\\.85\\\\.47:9703|46\\\\.4\\\\.123\\\\.170:9702\",job=\"Kusama\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Astar RPC2 Peers",
   "type": "timeseries",
   "description": "Total Number of P2P Peers\nHost = 46.4.123.170",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"astar\",job=\"astar-parachain\",instance=\"46.4.123.170:9615\"}",
     "legendFormat": "Astar Rpc2"
    }
   ]
  },
  {
   "title": "Aleph-Zero  Peers",
   "type": "timeseries",
   "description": "Total Number of P2P Peers",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"mainnet\",job=\"aleph-zero\",instance=\"46.4.123.170:9742\"}",
     "legendFormat": "Astar RPC1 Peers"
    }
   ]
  },
  {
   "title": "Westend ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"westend2\",instance=\"46.4.123.170:9743\",job=\"westend\"}",
     "legendFormat": "Westend Node"
    }
   ]
  },
  {
   "title": "Polkadot Peers",
   "type": "timeseries",
   "description": "Total Number of P2P Peers",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "polkadot_parachain_peer_count{chain=\"polkadot\",instance=~\"162\\\\.55\\\\.85\\\\.47:9616|46\\\\.4\\\\.123\\\\.170:9616\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Astar RPC1 Peers",
   "type": "timeseries",
   "description": "Total Number of P2P Peers",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{instance=~\"162\\\\.55\\\\.85\\\\.47:9615|46\\\\.4\\\\.123\\\\.170:9615\",job=\"astar-parachain\"}",
     "legendFormat": "Astar RPC1 Peers"
    }
   ]
  },
  {
   "title": "Nodle Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"para_eden\",instance=\"162.55.85.47:9742\",job=\"nodle\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Moonriver Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"ksmcc3\",instance=\"65.109.38.38:9201\",job=\"moonriver\"}",
     "legendFormat": "Moonriver"
    }
   ]
  },
  {
   "title": "Acala Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"acala\",instance=\"10.0.1.50:9727\",job=\"acala\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Karura Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"karura\",instance=\"46.4.123.170:9929\",job=\"karura\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Subquery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Admin URL ",
   "type": "stat",
   "description": "This tests the subquery coordinator by requesting GraphQl data via the web admin URL from an external location.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "accountMetadata",
     "endTimePath": "endTime",
     "queryText": "query {\n  accountMetadata {\n    __value: network\n    __text: network\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true
  }
 ]
}